// Encounter Editor -- authors encounter config JSON (docs/encounter-config.md).
// Graph view (LiteGraph, see memory) is the primary editing surface and the
// source of truth; JSON view is a read-only syntax-highlighted preview of
// what Save would write, generated by src/encounters/compile.ts. It's a
// <pre><code> block, not an editable field -- there's deliberately no
// second way to edit the document that could drift from the graph.

import { invoke } from "@tauri-apps/api/core";
import { open, save, message } from "@tauri-apps/plugin-dialog";
import { LGraph, LGraphCanvas } from "@comfyorg/litegraph";
import "@comfyorg/litegraph/style.css";
import hljs from "highlight.js/lib/core";
import jsonLang from "highlight.js/lib/languages/json";
import type { EncounterConfig } from "../encounters/schema";
import { CompileError, configToGraph, graphToConfig } from "../encounters/compile";
import { findInfoNode, registerEncounterNodeTypes, resetGraphWithInfoNode } from "../encounters/nodes";

hljs.registerLanguage("json", jsonLang);

function slugify(text: string): string {
  return text
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

let currentPath: string | null = null;
let wired = false;
let showJson = false;
let graph: LGraph | null = null;
let graphCanvas: LGraphCanvas | null = null;

function elements() {
  const json = document.querySelector<HTMLElement>("#encounter-editor-json");
  const jsonCode = document.querySelector<HTMLElement>("#encounter-editor-json-code");
  const status = document.querySelector<HTMLElement>("#encounter-editor-status");
  const newBtn = document.querySelector<HTMLButtonElement>("#encounter-editor-new-btn");
  const openBtn = document.querySelector<HTMLButtonElement>("#encounter-editor-open-btn");
  const saveBtn = document.querySelector<HTMLButtonElement>("#encounter-editor-save-btn");
  const tidyBtn = document.querySelector<HTMLButtonElement>("#encounter-editor-tidy-btn");
  const jsonToggleBtn = document.querySelector<HTMLButtonElement>(
    "#encounter-editor-json-toggle-btn",
  );
  const graphContainer = document.querySelector<HTMLElement>("#encounter-editor-graph");
  const canvasEl = document.querySelector<HTMLCanvasElement>("#encounter-editor-canvas");
  if (
    !json ||
    !jsonCode ||
    !status ||
    !newBtn ||
    !openBtn ||
    !saveBtn ||
    !tidyBtn ||
    !jsonToggleBtn ||
    !graphContainer ||
    !canvasEl
  ) {
    return null;
  }
  return { json, jsonCode, status, newBtn, openBtn, saveBtn, tidyBtn, jsonToggleBtn, graphContainer, canvasEl };
}

function ensureGraph(canvasEl: HTMLCanvasElement): LGraph {
  if (graph) return graph;
  registerEncounterNodeTypes();
  graph = new LGraph();
  graphCanvas = new LGraphCanvas(canvasEl, graph);
  graphCanvas.startRendering();
  return graph;
}

function resizeGraphCanvas(container: HTMLElement): void {
  if (!graphCanvas) return;
  // Buffer = CSS size * dpr (the standard crisp-canvas technique).
  const dpr = window.devicePixelRatio || 1;
  graphCanvas.resize(container.clientWidth * dpr, container.clientHeight * dpr);
  // The foreground canvas's compositing step (drawFrontCanvas) draws the
  // background/grid canvas back onto it at 1/devicePixelRatio size,
  // assuming the foreground context already carries a persistent dpr
  // scale -- the code path that would normally set that up is gated
  // behind a non-standard `ctx.start2D` method plain browsers don't have.
  // Setting the canvas's width/height (inside resize(), above) always
  // resets its transform to identity, so this has to be re-applied after
  // every resize, not just once at construction. setTransform (absolute)
  // rather than scale (relative) keeps this idempotent even when resize()
  // turns out to be a no-op.
  graphCanvas.ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
}

/** Resize now, then again after layout settles -- LiteGraph's resize() is a
 *  no-op when the new size matches the canvas's current (initially 300x150)
 *  size, so a single measurement taken before the flex layout has finished
 *  settling can leave the canvas stuck small. */
function resizeGraphCanvasSettled(container: HTMLElement): void {
  resizeGraphCanvas(container);
  requestAnimationFrame(() => resizeGraphCanvas(container));
}

/** Renders `text` as syntax-highlighted JSON into `jsonCode`. */
function setJsonText(jsonCode: HTMLElement, text: string): void {
  jsonCode.innerHTML = hljs.highlight(text, { language: "json" }).value;
}

/** Recompiles the graph into the JSON preview, or shows a placeholder
 *  explaining why it can't (a CompileError -- an unfinished graph, not a
 *  bug) rather than leaving stale JSON on screen. */
function refreshJsonPreview(jsonCode: HTMLElement, g: LGraph, status: HTMLElement): void {
  const info = findInfoNode(g);
  if (!info) {
    jsonCode.textContent = "";
    return;
  }
  try {
    setJsonText(jsonCode, JSON.stringify(graphToConfig(info), null, 2));
  } catch (err) {
    jsonCode.textContent = err instanceof CompileError ? `// ${err.message}` : `// ${String(err)}`;
    if (err instanceof CompileError) setStatus(status, `Can't compile: ${err.message}`);
  }
}

function setView(
  json: HTMLElement,
  graphContainer: HTMLElement,
  toggleBtn: HTMLButtonElement,
): void {
  json.hidden = !showJson;
  graphContainer.hidden = showJson;
  toggleBtn.setAttribute("aria-pressed", String(showJson));
  if (!showJson) resizeGraphCanvasSettled(graphContainer);
}

async function encountersDir(): Promise<string | undefined> {
  try {
    return await invoke<string>("encounters_dir_path");
  } catch {
    return undefined;
  }
}

function setStatus(status: HTMLElement, text: string): void {
  status.textContent = text;
}

function fileNameOf(path: string): string {
  return path.split(/[/\\]/).pop() ?? path;
}

export function renderEncounterEditor(): void {
  const els = elements();
  if (!els) return;
  const { json, jsonCode, status, newBtn, openBtn, saveBtn, tidyBtn, jsonToggleBtn, graphContainer, canvasEl } =
    els;

  const g = ensureGraph(canvasEl);
  if (!findInfoNode(g)) {
    resetGraphWithInfoNode(g, { zone: 0, id: "", name: "", difficulty: "mythic" });
    setStatus(status, "New encounter (unsaved)");
  }
  refreshJsonPreview(jsonCode, g, status);

  setView(json, graphContainer, jsonToggleBtn);

  if (wired) return;
  wired = true;

  new ResizeObserver(() => resizeGraphCanvasSettled(graphContainer)).observe(graphContainer);

  jsonToggleBtn.addEventListener("click", () => {
    showJson = !showJson;
    if (showJson) refreshJsonPreview(jsonCode, g, status);
    setView(json, graphContainer, jsonToggleBtn);
  });

  tidyBtn.addEventListener("click", () => {
    g.arrange();
    graphCanvas?.setDirty(true, true);
  });

  newBtn.addEventListener("click", () => {
    currentPath = null;
    resetGraphWithInfoNode(g, { zone: 0, id: "", name: "", difficulty: "mythic" });
    refreshJsonPreview(jsonCode, g, status);
    setStatus(status, "New encounter (unsaved)");
  });

  openBtn.addEventListener("click", () => {
    void (async () => {
      const picked = await open({
        multiple: false,
        directory: false,
        defaultPath: await encountersDir(),
        filters: [{ name: "Encounter", extensions: ["json"] }],
      });
      if (typeof picked !== "string") return;
      try {
        const text = await invoke<string>("read_encounter_text", { path: picked });
        const doc = JSON.parse(text) as EncounterConfig;
        const warnings = configToGraph(g, doc);
        currentPath = picked;
        refreshJsonPreview(jsonCode, g, status);
        setStatus(status, fileNameOf(picked));
        if (warnings.length) {
          await message(warnings.map((w) => w.message).join("\n"), {
            title: "Opened with warnings",
            kind: "warning",
          });
        }
      } catch (err) {
        await message(String(err), { title: "Open Encounter", kind: "error" });
      }
    })();
  });

  saveBtn.addEventListener("click", () => {
    void (async () => {
      const info = findInfoNode(g);
      if (!info) {
        await message("No Encounter Info node in the graph.", { title: "Save Encounter", kind: "error" });
        return;
      }
      let config: EncounterConfig;
      try {
        config = graphToConfig(info);
      } catch (err) {
        await message(err instanceof CompileError ? err.message : String(err), {
          title: "Can't save yet",
          kind: "error",
        });
        return;
      }
      const text = JSON.stringify(config, null, 2);

      let path = currentPath;
      if (!path) {
        const dir = await encountersDir();
        const zone = info.properties.zone;
        const idSlug = slugify(info.properties.id);
        const suggested =
          dir && zone > 0 && idSlug
            ? `${dir}/${zone}/${idSlug}.${info.properties.difficulty}.json`
            : dir;
        const picked = await save({
          defaultPath: suggested,
          filters: [{ name: "Encounter", extensions: ["json"] }],
        });
        if (!picked) return;
        path = picked;
      }
      try {
        await invoke("save_encounter_text", { path, json: text });
        currentPath = path;
        setJsonText(jsonCode, text);
        setStatus(status, fileNameOf(path));
      } catch (err) {
        await message(String(err), { title: "Save Encounter", kind: "error" });
      }
    })();
  });
}
